// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbcngsspowbwyqyqcohj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiY25nc3Nwb3did3lxeXFjb2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDcxNTgsImV4cCI6MjA2MDkyMzE1OH0.RRb_FeeKXMsIYyMIG1W1g3RmrUwl4633Rovbd515elc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);